FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_USER=$N8N_BASIC_AUTH_USER
ENV N8N_BASIC_AUTH_PASSWORD=$N8N_BASIC_AUTH_PASSWORD
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV WEBHOOK_TUNNEL_URL=$WEBHOOK_TUNNEL_URL
ENV N8N_ENCRYPTION_KEY=$N8N_ENCRYPTION_KEY

EXPOSE 5678
